name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies with pnpm
        uses: ./.github/actions/pnpm

      - name: Build other packages
        run: pnpm -r --filter !client build

      - name: Test
        run: pnpm --filter core test

      - name: Build the GitHub pages distribution
        run: VITE_DEPLOY_TO_GH=true pnpm --filter client build

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_ACTIONS_DEPLOY_KEY }}
          publish_dir: ./packages/client/build
